### ISSUE TITLE
TypolinkViewHelper problem

### ISSUE THREAD

**Issue by mcmz** [jonathanheilmann/ext-jh_pdfviewer#10]
Hi Jonathan,

in typo3 6.2 i see the following error message after installation:
Could not analyse class:TYPO3\CMS\Fluid\ViewHelpers\Link\TypolinkViewHelper maybe not loaded or no autoloader

Any ideas bout this? Maybe a misspelled TypolinkViewHelper in fluid?

Best regards

**Comment by jonathanheilmann** [comment]
Oh, this viewhelper is available in TYPO3 CMS 7.6 LTS only.
I'll update the extension, providing a backport of this viewhelper.
